# Resource mode is saved by the internal test switch (default: offline).
candyhouse.sesame.web.dev=http://localhost:3000
candyhouse.sesame.web.prod=https://pre-app-h5.d36dwtby1bef9y.amplifyapp.com

# AWS Cognito Configuration
aws.cognito.identityPoolId=ap-northeast-1:0a1820f1-dbb3-4bca-9227-2a92f6abf0ae
aws.cognito.userPoolId=ap-northeast-1_bY2byhlCa
aws.cognito.appClientId=6ialca0p8u0lsgvbmvsljfm305

# Google Maps Android API
google.maps.apiKey=YOUR_GOOGLE_MAP_KEY