[versions]
agp = "9.4.1"
ksp = "2.3.7"
androidxActivity = "1.9.0"
amplifyAndroid = "2.38.1"
core = "3.3.3"
desugarJdkLibs = "2.1.5"
kotlinxCoroutinesAndroid = "1.7.3"
lifecycleRuntimeKtx = "2.8.6"
roomRuntime = "2.7.1"
firebaseBom = "33.4.0"
androidxAnnotation = "1.8.1"
gson = "2.10.1"
googleServices = "4.4.2"
firebaseCrashlytics = "3.0.3"
dfu = "2.5.0"
playServicesLocation = "21.3.0"
playServicesMaps = "19.0.0"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidxActivity" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesAndroid" }
androidx-lifecycle-livedata-core = { module = "androidx.lifecycle:lifecycle-livedata-core", version.ref = "lifecycleRuntimeKtx" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
amplify-aws-auth-cognito = { module = "com.amplifyframework:aws-auth-cognito", version.ref = "amplifyAndroid" }
amplify-core-kotlin = { module = "com.amplifyframework:core-kotlin", version.ref = "amplifyAndroid" }
core = { module = "com.google.zxing:core", version.ref = "core" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
dfu = { module = "no.nordicsemi.android:dfu", version.ref = "dfu" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }

[plugins]
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
