# API Gateway(Login Authentication)
MobileLoginAPI_DEV=https://0dkzum4jzg.execute-api.ap-northeast-1.amazonaws.com/dev
MobileLoginAPI_PROD=https://0dkzum4jzg.execute-api.ap-northeast-1.amazonaws.com/prod

# AWS Cognito
aws.cognito.identityPoolId=ap-northeast-1:0a1820f1-dbb3-4bca-9227-2a92f6abf0ae
aws.cognito.userPoolId=ap-northeast-1_bY2byhlCa
aws.cognito.appClientId=6ialca0p8u0lsgvbmvsljfm305

# Google Maps API Key
google.maps.apiKey=YOUR_GOOGLE_MAP_KEY